name: Build Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker build (no push)
        run: |
          docker build -t temp-image:${{ github.sha }} .
